version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: revvo
      POSTGRES_USER: revvo
      POSTGRES_PASSWORD: revvo123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  php:
    image: php:8.2-apache
    container_name: revvo-php
    depends_on:
      - db
    volumes:
      - ./backend:/var/www/html
    ports:
      - "8000:80"
    environment:
      DB_HOST: db
      DB_NAME: revvo
      DB_USER: revvo
      DB_PASS: revvo123
    restart: always
volumes:
  pgdata: 