version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: revvo
      POSTGRES_USER: revvo
      POSTGRES_PASSWORD: revvo123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/01-init.sql
      - ./init_data.sql:/docker-entrypoint-initdb.d/02-data.sql
  php:
    build: .
    container_name: revvo-php
    depends_on:
      - db
    volumes:
      - .:/var/www/html
    ports:
      - "8000:80"
    environment:
      DB_HOST: db
      DB_NAME: revvo
      DB_USER: revvo
      DB_PASS: revvo123
    restart: always
volumes:
  pgdata: 